(function(){
'use strict';

// Modularized this code for reuse in pseudoIso
var getStplsTranslate = function(){
  var stplsTranslate;
  try {
    stplsTranslate = angular.module('stplsTranslate');
  } catch (e){
    stplsTranslate = angular.module('stplsTranslate',['pascalprecht.translate']);
  }
  return stplsTranslate;
};

getStplsTranslate().config(['$translateProvider', function ($translateProvider) {

    $translateProvider.translations('en_US', {
        'ACT_NEW': 'New to Staples?',
        'ACT_CR_NEW': 'Create a New Account',
        'ACT_PRF': 'PROFILE',
        'ACT_ES_RORD': 'EASY REORDER',
        'ACT_FAV_LIST': 'FAVORITES LIST',
        'ACT_ORDS': 'ORDERS',
        'ACT_RWDS': 'REWARDS',
        'ACT_CRT_ACT': 'Create a Staples.com® Account',
        'ACT_ACT': 'Account',
        'ACT_IND_REQ_INFO': 'Indicates required information',
        'ACT_EML_ADD': 'Email Address',
        'ACT_NTFY_DEAL': 'Notify me about deals and specials',
        'ACT_UNME': 'Username',
        'ACT_PWD': 'Password',
        'ACT_RENTR_PWD': 'Re-Enter Password',
        'ACT_LGN_AUTO': 'Log me in automatically',
        'ACT_STPL_RWD1': 'Staples Rewards ',
        'ACT_STPL_RWD2': ' (optional)',
        'ACT_STPL_RWD_NBR': 'Staples Rewards Number',
        'ACT_ALREADY_MBM': 'Already a member',
        'ACT_RWD_SIGNUP': 'Become a member',
        'ACT_NT_NW': 'Not now',
        'ACT_RWD_NUM_ERR': 'Rewards number should only contain numbers',
        'ACT_SUBMIT': 'Submit',
        'ACT_PASSWORD_ERROR': 'Password must meet these requirements: 8 character minimum, case sensitive, and contain at least 3 of these combinations: uppercase letter, lowercase letter, number or special characters #?!@$%^&*-.',
        'ACT_OLDPASSWORD_MINERROR': 'Old password must be minimum of 6 characters.',
        'ACT_OLDPASSWORD_MAXERROR': 'Maximum password length is 255 characters.',
        'ACT_OLDPASSWORD_INVALIDCHAR': 'Password contains invalid characters.',
        'ACT_OLDPASSWORD_REQUIRED': 'This field is required.',
        'ACT_CONTINUE_SHOPPING': 'Continue Shopping',
        'ACT_RESET_ERROR': 'There was an error calling reset on your password.  Please verify your password and try again.',

        'ADR_HEADER': 'Address(es) Stored',
        'ADR_ADD_ADDR_BTN': '+ Add Address',
        'ADR_SHIPPING_ADDR_BTN': 'Add new shipping address',
        'ADR_BILLING_ADDR_BTN': 'Add new billing address',
        'ADR_EDIT_HEADER': 'Edit Address',
        'ADR_ADD_HEADER': 'Add Address',
        'ADR_FIRSTNAME_PH': 'First Name*',
        'ADR_LASTNAME_PH': 'Last Name*',
        'ADR_NAME_PH': 'Full Name (First Last)*',
        'ADR_COMPANY_PH': 'Company',
        'ADR_ADDRESS': 'Address',
        'ADR_STREET1_PH': 'Address Line 1*',
        'ADR_STREET2_PH': 'Apt/Suite',
        'ADR_CITY_PH': 'City/Town*',
        'ADR_ZIP_PH': 'Zip*',
        'ADR_PHONE_PH': 'Telephone Number*',
        'ADR_PHONE_EXT_PH': 'Ext.',
        'ADR_MANAGE': 'Manage Addresses',
        'ADR_INVALID_NAME': 'Please enter a name as \'First Last\' with only alpha characters.',
        'ADR_INVALID_ADDRESS': 'Please enter or choose a valid address.',
        'ADR_INVALID_ADDRESSENTRY': 'Please select a google address or use the dropdown entry form.',
        'ADR_INVALID_FIRST': 'Full Name is missing or invalid.  Please try again.',
        'ADR_INVALID_LAST': 'Last name is missing or invalid.  Please try again.',
        'ADR_INVALID_LINE1': 'Address line 1 is missing or invalid.  Please try again.',
        'ADR_INVALID_CITY': 'City name is missing or invalid.  Please try again.',
        'ADR_INVALID_STATE': 'State is missing or invalid.  Please try again.',
        'ADR_INVALID_ZIP': 'Zip code is missing or invalid.  Please try again.',
        'ADR_INVALID_PHONE': 'Phone number is missing or invalid.  Please try again.',
        'ADR_ADDRESS_DELETED': 'Address is deleted from profile.',
        'ADR_ADDRESS_DELETE_CURRENT': 'You cannot delete a currently selected address.',
        'ADR_DELETE_ERROR': 'Oops, there\'s been a problem. Please try again.',

        'ATC_COUPON_ADDED': 'Coupon Added to Cart',
        'ATC_ITEMS_ADDED': 'Items Added to Cart',
        'ATC_ERR_NOITEMS': 'Missing SKU or Coupon',

        'BRW_HEADER': 'SHOP BY CATEGORY',

        'CANCEL': 'Cancel',

        'CART_SEEPRICE': 'See Price in Cart',
        'CART_INVERROR': 'We\'re sorry. This store currently has %qtyValue% quantity available for in-store pickup.',
        'CART_SKUSETMASTER': 'Sorry, this item is a SkuSet master. Only its sub-items can be ordered.',
        'CART_INSTORE_ONLY': 'Sorry, this item is available in-store only.',
        'CART_INSTORE_ONLY_OOS': 'Sorry, there is insufficient quantity in nearby stores.',
        'CART_DOTCOM_ONLY': 'Sorry, this item is not available for purchase using the mobile app.  Please visit Staples.com.',
        'CART_OOS_ONLINE': 'Sorry, this item is currently out-of-stock online.',
        'CART_OOS': 'Sorry, item is out of stock.',
        'CART_ERROR_TITLE': 'Error adding item to cart',
        'CART_CLOSE': 'Close',
        'CART_EMPTY_BTN': 'Get shopping!',
        'CART_CONTINUE': 'Keep shopping',
        'CART_VIEW': 'View cart',
        'CART_CHECKOUT': 'Checkout',
        'CART_EMPTY_COUPON': 'Please enter a 5-16 digit coupon code.',
        'CART_TOTAL_LABEL': 'Pre-Tax Total',
        'CART_TOTAL_ITEM': ' item)',
        'CART_TOTAL_ITEMS': ' items)',
        'CART_ADD_TO_FREE_SHIP': 'Add <strong>{{value | currency:\'$\'}}</strong> to qualify for free shipping.',
        'CART_MIN_BASKET_SHIP': '<b>Item(s) in your cart</b> only ship with orders of ${{min}} or more.<br> Your cart currently contains {{subtot | currency:\'$\'}}.',
        'CART_ADDON_SHIP': '<b>{{addon}} of the {{count}} Item(s) in your cart</b> only ship with orders of ${{min}} or more.<br> Your cart currently contains {{subtot | currency:\'$\'}}.',
        'CART_FREE_SHIPPING': 'You qualify for <strong>free shipping</strong>!',
        'CART_FREE_SHIPPING_REWARDS': 'Free shipping for Rewards members on orders over $14.99',
        'CART_DEFAULT_ERROR': 'Oops, there\'s been a problem. Please try again.',
        'CART_OOS_BOPISERROR': 'Oops. Looks like this item is only available for pickup at this time.',
        'CART_OOS_NONBOPISERROR': 'Oops. Looks like this item is currently out of stock online.',
        'SECURE_CHECKOUT': 'Secure Checkout',
        'CART_REM_PREF': 'Remember my preference',
        'CART_OTHER_OPTIONS': 'Other Options',
        'CART_STPLS_CHECKOUT': 'Staples Checkout',
        'CC_CARDS_HEADER': 'Credit Card(s) Stored',
        'CC_ADD_CARD_BTN': 'Add new card',
        'CC_EXP_DATE': 'Expiration Date: ',
        'CC_EXP': 'Expires ',
        'CC_NOTE': 'Note: ',
        'CC_NOTE_PH': 'Notes',
        'CC_EDIT_BTN': 'Edit',
        'CC_DELETE_BTN': 'Delete',
        'CC_SAVE_BTN': 'Save',
        'CC_CANCEL_BTN': 'Cancel',
        'CC_EDIT_HEADER': 'Edit Credit Card',
        'CC_ADD_HEADER': 'Add Credit Card',
        'CC_REQUIRED_INFO': ' Indicates required information',
        'CC_CARDTYPE_MC': 'Mastercard',
        'CC_CARDTYPE_VISA': 'Visa',
        'CC_CARDTYPE_AMEX': 'AMEX',
        'CC_CARDTYPE_STAPLES': 'Staples',
        'CC_CARDTYPE_DISC': 'Discover',
        'CC_MANAGE': 'Manage Credit Cards',
        'CC_NUM_REENTER': 'You must re-enter your credit card number for all changes.',
        'CC_NUM_ERROR': 'Credit card number is missing or invalid.  Please try again.',
        'CC_VEND_ERROR': 'Unsupported credit card vendor.  Please choose another card.',
        'CC_DATE_ERROR': 'Expiration date is missing or not a date in the future.  Please try again.',
        'CC_CVV_ERROR': 'Card CVV code is missing or invalid.  Please try again.',
        'CC_NOTES_ERROR': 'Card Notes cannot be greater than 32 characters.  Please try again.',
        'CC_PROCESS_ERROR': 'An error occurred processing this creditcard.  Please try again later.',
        'CC_DELETE_ERROR': 'An error occurred deleting this creditcard.  Please try again later.',
        'CC_DELETE_CURRENT': 'You cannot delete a currently selected credit card.',
        'CC_CARD_DELETED': 'Credit card is deleted from profile.',

        'CHK_HEADER': 'Checkout',
        'CHK_SHIPPING_ADD_HEAD': 'Shipping address',
        'CHK_PAYMENT_METHOD_HEAD': 'Payment method',
        'CHK_VALID_SHIP_TEXT': 'Validate Shipping Address',
        'CHK_VALID_BILL_TEXT': 'Validate Billing Address',
        'CHK_STREET_ADDR_PH': 'Street Address',
        'CHK_APT_PH': 'Apt/Bldg (optional)',
        'CHK_CITY_PH': 'City',
        'CHK_STATE_DEFAULT': 'St*',
        'CHK_ZIP_PH': 'Zip',
        'CHK_CONTINUE_BTN': 'Continue',
        'CHK_CART_ERROR': 'Unable to obtain the shopping cart.  Please contact Staples Customer Service.',
        'CHK_RTN_CUST_QUEST': 'Returning customer?',
        'CHK_SIGNIN': 'Sign In',
        'CHK_NAME_PH': 'Full Name (First Last)',
        'CHK_SHIP_ADDR_PH': 'Shipping Address',
        'CHK_PHONE_PH': 'Phone',
        'CHK_EMAIL_PH': 'Email',
        'CHK_CC_PH': '{{expand ? \'1234 5647 8901 2345\':\'Credit card number\'}}',
        'CHK_EXP_PH': 'MM/YY',
        'CHK_CVV_PH': 'CVV',
        'CHK_VISA_IMG_ALT': 'Visa Checkout by Visa',
        'CHK_BILL_USE_DIFF_QUEST': 'Use a different billing address?',
        'CHK_BILL_USE_AS': 'Billing address is same as shipping',
        'CHK_ONLABEL': 'Yes',
        'CHK_OFFLABEL': 'No',
        'CHK_CC_HOLDER_NAME_PH': 'Card Holder Name',
        'CHK_BILL_ADDR_PH': 'Billing Address',
        'CHK_PROD_TOTAL': 'Subtotal',
        'CHK_COUPON_TOTAL': 'Coupons & Rewards',
        'CHK_SHIPPING_TOTAL': 'Shipping',
        'CHK_OVERSIZE_SHIPPING_FEE': 'Oversize Shipping Fees',
        'CHK_FREE': 'FREE',
        'CHK_TAX': 'TAX',
        'CHK_SUB': 'Sub-Total',
        'CHK_EST_TAX': 'Estimated Tax',
        'CHK_TOTAL_AMT': 'Total',
        'CHK_PLACE_ORDER_BTN': 'Place Order',
        'CHK_UPD_PAYMENT_MSG': 'Updating payment information ...',
        'CHK_UPD_ORDER_MSG': 'Updating order information ...',
        'CHK_VER_ORDER_MSG': 'Verifying order ...',
        'CHK_SUB_ORDER_MSG': 'Submitting order ...',
        'CHK_UPD_SHIP_MSG': 'Updating shipping address ...',
        'CHK_UPD_BILL_MSG': 'Updating billing address ...',
        'CHK_CALC_TAX_MSG': 'Calculating tax ...',
        'CHK_PICKUPNAME_PH': 'Alternate Pickup Person (First Last)',
        'CHK_PICKUPPHONE_PH': 'Pickup Person Phone',
        'CHK_ERROR_SHIPPING': 'Error updating shipping address. Service may be temporarily unavailable.',
        'CHK_ERROR_BILLING': 'Error updating billing address. Service may be temporarily unavailable.',
        'CHK_ERROR_PRECHK': 'Error during pre-checkout. Service may be temporarily unavailable.',
        'CHK_ERROR_TAX': 'Error calculating tax. Service may be temporarily unavailable.',
        'CHK_ERROR_PAYMENT': 'Error updating payment. Service may be temporarily unavailable.',
        'CHK_ERROR_ORDER': 'Error submitting order. Service may be temporarily unavailable.',
        'CHK_ERROR_ENCRYPT': 'Error encrypting credit card. Service may be temporarily unavailable.',
        'CHK_ERROR_CCADD': 'Error adding credit card. Service may be temporarily unavailable.',
        'CHK_ERROR_UPDATE':  'Error during update. Services may be temporarily unavailable.',
        'CHK_ERROR_ADDRESS': 'Please enter all parts of the address.',
        'CHK_SHIP_ADDRESS_ERROR': 'Please select a shipping address from the dropdown of addresses.',
        'CHK_SHIP_STATE_ERROR': 'Please enter a valid state code in the shipping address.',
        'CHK_BILL_ADDRESS_ERROR': 'Please select a billing address from the dropdown of addresses.',
        'CHK_GUEST_MUST_SIGNIN_ERROR': 'One or more items in your cart prevents guest checkout. Please sign in or create an account to continue.',
        'CHK_ERROR_CVC': 'Please verify that the card number, expiration date and CVV number are correct.',
        'CHK_ERROR_EXPIRY': 'Expiration Date is invalid.  Please enter a valid date in the future.',
        'CHK_ERROR_TRANSACTION': 'If this problem persists, please call us at 1-800-STAPLES (1-800-782-7537) to speak with an associate.',
        'CHK_BOPIS_STORE_LABEL': 'Pickup Stores...',

        'CLS_MORE_INFO': 'READ MORE +',
        'CLS_LESS_INFO': 'READ LESS -',
        'CLS_BEST_MATCH': 'Best Match',
        'CLS_TOP_RATED': 'Top Rated',
        'CLS_PRICE': 'Price',
        'CLS_NAME': 'Name',
        'CLS_ITEM_FOUND': 'item found',
        'CLS_ITEMS_FOUND': 'items found',
        'CLS_NO_ITEMS_FOUND': 'No items found',
        'CLS_FILTER': 'Filter',
        'CLS_APPLY': 'Apply',
        'CLS_FILTER_SHOWMORE': 'Show Additional Filters',
        'CLS_BOPIS_TAG': '1hr pick up',
        'CLS_NOT_FOUND_START': 'Your search for "',
        'CLS_NOT_FOUND_END': '" did not match any products',
        'CLS_NOT_FOUND_START2': ' (0 items found), ',
        'CLS_FREE_SHIPPING': 'Free Shipping',
        'CLS_RETAIL_SKU': 'in-store only',

        'CFM_BOPIS_MSG': 'Give us a moment, we\'ll email you when your items are ready to be picked up in store.',
        'CFM_PU_MSG': 'Pick up item(s) at:',

        'DD_SOLDCOUNT': 'Over <strong>{{count}}</strong> sold',
        'DD_SAVE': 'Save {{savings}}%',
        'DD_SAVE_UPTO': 'Save up to {{savings}}%',
        'DD_TIME_LEFT': 'left to buy',
        'DD_EXPIRED': 'Sorry, this deal has expired.',

        'EST_DELIVERY': 'Estimated delivery',

        'FB_MESSAGE': 'Chat with us',

        'FT_FIND_STORE': 'Find a Store',
        'FT_TERMS': 'Privacy & Terms',
        'FT_ABOUT_LINK': 'About',
        'FT_HELP': 'Help',
        'FT_LOGIN': 'Login',
        'FT_FEEDBACK': 'Feedback',
        'FT_FREESHIP': 'Free shipping',
        'FT_EVERYDAY': 'every day*',
        'FT_PRMATCH': 'Price match',
        'FT_GUARANTEE': 'guarantee**',
        'FT_EZRTN': 'Easy returns',
        'FT_ALWAYSFREE': 'always free',
        'FT_FREESHIP_INFO': '*Free shipping for Staples Rewards members on orders over $14.99. Excludes oversized items.',
        'FT_PRMATCH_INFO': '**We\'ll price match any competitor with an online and retail store -- plus Amazon.',

        'GEN_INVALID_CHAR': 'Invalid characters entered.',
        'GEN_MIN_LENGTH': 'Minimum length not satisfied.',
        'GEN_MAX_LENGTH': 'Maximum length exceeded.',
        'GEN_REQUIRED': 'This field is required.',
        'GEN_EMAIL_INVALID': 'Invalid email address.',
        'GEN_SAVE_BTN': 'Save',
        'GEN_CANCEL_BTN': 'Cancel',
        'GEN_DONE_BTN': 'Done',
        'GEN_CONTINUE_BTN': 'Continue',
        'GEN_SEE_MORE': 'See More',
        'GEN_SEE_LESS': 'See Less',
        'GO_TO_CART': 'Go to cart',

        'HOME_DESC': 'Staples makes it easy to make more happen with more products and more ways to shop. Through its world-class retail, online and delivery capabilities. Staples lets customers shop however and whenever they want, whether it’s in store, online, or on mobile devices. Staples offers more products than ever, in categories such as technology, facilities and breakroom, furniture, safety, and medical, as well as Copy & Print and Staples® EasyTech™ services. Staples has been making it easy for businesses for 27 years with thousands of associates worldwide. Headquartered outside Boston, Staples operates throughout North and South America, Europe, Asia, Australia and New Zealand. More information about Staples (NASDAQ: SPLS) is available at staples.com®',

        'INK_HEADER': 'Ink & Toner Finder',
        'INK_SEARCH_PH': 'Search by Cartridge # or printer name',
        'INK_BRAND_HEADER': 'Search by Brand',
        'INK_SEEALL_LINK': 'See all',
        'INK_SEARCH_ERROR': 'No search results found for cartridges or printers.  Please try again.',

        'INV_NOTHING_FOUND': 'No inventory found within 20 miles of this location.',
        'INV_QTY_DISCLAIMER': 'Store quantity is accurate as of the time the item is added to cart. Product availability is subject to change.',
        'INV_ZIP_INSTRUCT': 'Please enter a valid US zipcode.',
        'INV_FIND_INSTRUCT': 'Find this item at a different store:',
        'INV_PU_INSTRUCT': 'Pick up in store today',
        'INV_YOUR_STORE': 'Your store:',
        'INV_BOPIS_UPDATE_ERROR': 'Error updating store.  Please try again later.',

        'LCR_MON': 'Mon',
        'LCR_TUE': 'Tues',
        'LCR_WED': 'Wed',
        'LCR_THU': 'Thurs',
        'LCR_FRI': 'Fri',
        'LCR_SAT': 'Sat',
        'LCR_SUN': 'Sun',
        'LCR_MON_FRI':'Mon-Fri',

        'LCR_STORE': 'Store #',
        'LCR_ERROR_STR': 'No results found.',
        'LCR_ERROR_STORE': 'No match found for store #{{store}}',
        'LCR_HEADER': 'Store Finder',
        'LCR_SEARCH': 'City, State or Zip',
        'LCR_WITHIN': 'results within',
        'LCR_MY_STORE': 'My Store',
        'LCR_NO_REM_HEADER': 'You have not set your store yet.',
        'LCR_NO_REM_TEXT': 'Locate the store you wish to set as your store and select the checkbox to set as your store.',
        'LCR_CLOSEST': 'Closest To Me',
        'LCR_MAP': 'Map',
        'LCR_LIST': 'List',
        'LCR_NO_GEO_HEADER': 'Location detection is disabled',
        'LCR_NO_GEO_TEXT': 'Location detection is disabled or your device/browser software does not appear to support geolocation services. Please check your device/browser software settings and retry.',
        'LCR_SET_STORE': 'Set as my store',
        'LCR_BACK': 'Back',
        'LCR_DIR': 'Directions',
        'LCR_STR_HR': 'Store Hours',
        'LCR_PH': 'Store Phone',
        'LCR_STR_SRCH': 'Search this store',
        'LCR_STR_CPN': 'Coupons For This Store',
        'LCR_STR_AD': 'Weekly Ad For This Store',
        'LCR_STR_EV': 'Store Events',
        'LCR_STR_NO_EV': 'No events at this Store.',
        'LCR_STR_MAIL': 'Feedback For This Store',
        'LCR_REFINE': 'Refine',
        'LCR_RETRY': 'Retry',
        'LCR_SPECIAL': 'View special hours',
        'LCR_CHOOSE': 'Choose from one of these:',
        'LCR_STORES_GEO': 'Stores near your current location:',
        'LCR_STORES_ZIP': 'Stores near %zip%:',
        'LCR_STORES_STOCK_ZIP': 'Stores near %zip% with this item in stock:',
        'LCR_WAIT_STORES': 'Retrieving stores near your current location.',
        'LCR_NEAREST': 'Nearest Store',
        'LCR_CLOSED': 'Closed now',
        'LCR_OPEN': 'Open: ',
        'LCR_OPEN_UNTIL': 'Open now until ',

        'LGN': 'Sign in',
        'LGN_HEADER': 'Sign in to Staples.com',
        'LGN_SUB_HEADER': 'The fastest way to review your selections, access your Account information and submit your order.',
        'LGN_REM': 'Remember me',
        'LGN_FORGOT': 'Forgot your password?',
        'LGN_ATTEMP_LGN': 'Attempting login...',
        'LGN_FORGOT_PWD_HEADER': 'Login Assistance',
        'LGN_FORGOT_PWD_INFO': 'When you click submit, we will send an email to this address. In this email there will be a link. Click on this link to complete this process and reset your password.',
        'LGN_FORGOT_PWD_TEXT': 'Forgot Password',
        'LGN_ERROR_USERNAME': 'Username or Password is incorrect',
        'LGN_PWD_RESET_OK': 'A reset link was successfully sent to your email address.',
        'LGN_PWD_RESET_ERR': 'We\'re sorry but we can\'t find this email address. Please try again.',
        'LGN_RESET_MESSAGE': 'Due to system migration and security enhancements, we are requiring our customers to update their passwords.',
        'LGN_RESET_LINK': 'Reset password',
        'LGN_RESET_SUCCESS_MSG': 'We\'ve sent a link to reset your password.  Please check your email.',
        'LGN_RESET_SUCCESS_BTN': 'Ok, got it.',

        'ORD_HEADER': 'Purchase History',
        'ORD_DATE_HEAD': 'Order Date',
        'ORD_NUM_HEAD': 'Order #',
        'ORD_TOT_HEAD': 'Order Total',
        'ORD_SHOW_LBL': 'Show More',
        'ORD_DATE_LBL': 'Date: ',
        'ORD_NUM_LBL': 'Order No: ',
        'ORD_DATE_LBL2': 'Order Date: ',
        'ORD_TOT_LBL': 'Total Ordered: ',
        'ORD_STAT_LBL': 'Status: ',
        'ORD_PAYHIST_LBL': 'Payment History',
        'ORD_DELADDR_LBL': 'Delivery Address',
        'ORD_ITEMS_LBL': 'Order Items',
        'ORD_PAY_SUB_LBL': 'Subtotal:',
        'ORD_PAY_TAX_LBL': 'Tax:',
        'ORD_PAY_DEL_LBL': 'Delivery:',
        'ORD_PAY_TOT_LBL': 'Total Ordered:',
        'ORD_PAY_COUPON_LBL': 'Coupons & Rewards:',
        'ORD_WAIT_LBL': 'Retrieving orders ...',
        'ORD_DETWAIT_LBL': 'Retrieving order detail ...',
        'ORD_DETERR_LBL': 'Error retrieving detail for this order.',
        'ORD_NO_ORDERS': 'No online orders were found for your username.',
        'ORD_THKYOU': 'Thank you for your order.',
        'ORD_ORDNUM': 'Order Number: ',
        'ORD_EMAILINFO': 'A confirmation email will be sent to ',
        'ORD_DELTO': 'Deliver item(s) to:',
        'ORD_YOUBOUGHT': 'You purchased:',
        'ORD_ORDTOT': 'Order Total:',
        'ORD_PRODTOT': 'Sub-total:',
        'ORD_SHIPPING': 'Shipping & Handling:',
        'ORD_TAX': 'Estimated Tax:',
        'ORD_TOTAL': 'Total:',
        'ORD_CONTSHOP': 'Continue shopping',
        'ORD_MISTAKE': 'Made a mistake?',
        'ORD_CANCELINFO': 'Cancel your order within the next 10 minutes and it will not be processed.',
        'ORD_CANCELNOW': 'Cancel Order',
        'ORD_CONTACTUS': 'Contact Us',
        'ORD_THKAGAIN': 'Thank you for your order.  We appreciate your business.',
        'ORD_CREATE_ACCT_HDR': 'Create a staples.com account password',
        'ORD_PASS_PH': 'password',
        'ORD_CREATE_ACCT_BTN': 'Create my account',
        'ORD_SUBSCRIBE_ERR_EMPTY': 'Please complete at least one field to subscribe.',
        'ORD_SUBSCRIBE_TRY_AGAIN': 'Try again.',
        'ORD_ACCT_SUCCESS': 'Congratulations, your account has been created.',
        'ORD_ACCT_PROCESS_MSG': 'Creating your account and rewards membership...',

        'OPT_HDR': 'Sign up below for great deals.',
        'OPT_HDR2': 'Looking for our best deals?',
        'OPT_SUBHDR': 'Sign up below to get them delivered straight to your inbox or cell phone*.',
        'OPT_SIGNUP_BELOW': 'Sign up below.',
        'OPT_EMAIL_LBL': 'Deals by email',
        'OPT_EMAIL_PH': 'email address',
        'OPT_SMS_LBL': 'Deals by text message*',
        'OPT_SMS_PH': 'cell phone number',
        'OPT_SMS_CAVEAT': '*Message & data rates may apply',
        'OPT_EMAIL_SUCCESS': 'Subscribed at <strong>{{value}}</strong><br/> To unsubscribe, tap unsubscribe link in email.',
        'OPT_SMS_SUCCESS': 'Subscribed at <strong>{{value}}</strong><br/> To unsubscribe, text STOP to 555-444.',
        'OPT_ACTION': 'Subscribe',
        'OPT_SUCCESS_ACTION': 'Get Shopping',

        'PAY_CHECKOUT': 'Staples Checkout',
        'PAY_APPLEPAY': 'Apple Pay',
        'PAY_VME': 'VISA Checkout',
        'PAY_AMEXPAY': 'AMEX Pay (TBD)',
        'PAY_STPLS_LABEL': 'Staples, Inc',

        'PRC_NOW': 'Now',
        'PRC_DISCOUNT': '{{value}} %',
        'PRC_ASLOWAS': 'As low as {{price | currency}}',

        'PRF_SHIP': 'Currently Staples.com does not ship to P.O. Boxes, APO/FPO, Alaska(AK), Hawaii(HI), Puerto Rico(PR), or international addresses.',
        'PRF_HDR': 'Profile',
        'PRF_NNAME': 'Nickname',
        'PRF_NNAME_MSG': 'Enter new nickname',
        'PRF_UNAME': 'Username',
        'PRF_EMAIL_MSG': 'Enter new email address',
        'PRF_RECV': 'Receive ',
        'PRF_SPC_SAVE': 'Special Savings by Email',
        'PRF_UNSUB_REAS': 'Reason for Unsubscribe',
        'PRF_CC_LBL': 'Credit Cards',
        'PRF_CC_HDR': 'Credit Card(s) Stored',
        'PRF_ADR_LBL': 'Addresses',
        'PRF_ADR_HDR': 'Address(es) Stored',
        'PRF_RWD_HDR': 'Your Staples Rewards',
        'PRF_RWD_PH': 'Rewards Number',

        'PROD_ADS_HDR': 'Advertisement',
        'PROD_ATC_BTN': 'Add to cart',
        'PROD_ATC_BOTH_BTN': 'Add both to cart',
        'PROD_BOPIS_CHK_STORE': 'Check another store',
        'PROD_BOPIS_MSG': 'Pick up in store today',
        'PROD_BOPIS_STOCK': '{{value}} available at ',
        'PROD_BUYINSTORE_MSG': 'Buy in store today',
        'PROD_DEALS_HDR': 'Sign up for deals',
        'PROD_EXP_DEL_LBL': 'Expected Delivery:',
        'PROD_FREE_SHIPPING_INFO': 'Ships with any qualifying order over $%v%.',
        'PROD_FREQ_BOT_HDR': 'Frequently bought together:',
        'PROD_HELP_SHIP_POLICY': 'What is your delivery policy?',
        'PROD_HELP_SHIP_TO_STORE': 'Secure Checkout | Deliver to a store near me',
        'PROD_MINIMUM_TAG':' $%v% minimum',
        'PROD_MINIMUM': ' minimum',
        'PROD_OVERSIZ_SHIPPING_FEE': 'Oversize Shipping Fees',
        'PROD_OVERSIZE_SHIPPING_INFO': 'An additional shipping fee of $%v% will be added to the cart.',
        'PROD_OVERSIZED': 'oversized',
        'PROD_GETSTARTED_BTN': 'Get started',
        'PROD_PUTODAY_BTN': 'Pick up today',
        'PROD_REBATE': '${{value}} rebate',
        'PROD_SAVE_INSTANT': ' with instant discount. ',
        'PROD_SAVE_REBATE': ' with rebate. ',
        'PROD_SAVE': 'Save ',
        'PROD_SIM_PRODS_HDR': 'Similar products',
        'PROD_SUBS_BTN': 'Subscribe',
        'PROD_ADDED_TO_CART': '{{qty}} item(s) added to <a>cart</a>.',
        'PROD_WAS_ATC': '{{name}} was added to Cart',
        'PROD_ITEM_WAS_ATC': 'Item was added to Cart',
        'PROD_NOT_FOUND_MSG': 'The product {{sku}} was not found.  Please verify the sku and try again.',
        'PROD_TOTAL_PRICE': 'Total price:',
        'PROD_ULT_BOUGHT': 'Customers also viewed:',
        'PROD_BS_LINE': 'Business service delivery',

        'RWD_HEADER': 'Enroll Rewards',
        'RWD_TOT_SPEND': 'Total Spending',
        'RWD_TOT_YTD': '(YTD)',
        'RWD_INK_RECYCLE': 'Ink Recycling',
        'RWD_TOT_EARN': 'Total Earnings',
        'RWD_LAST_12': 'Last 12 Months',
        'RWD_EARNED':  'REWARDS EARNED',
        'RWD_EXPIRES': 'Exp. ',
        'RWD_VALUE': 'Value ',
        'RWD_ADDTO_CART': 'Add to Cart',
        'RWD_USEIN_STORE': 'Use In-Store',
        'RWD_LOGGEDIN_MSG': 'You must be logged in to view your Rewards.',
        'RWD_WAIT_MSG': 'Please wait while we gather your rewards...',
        'RWD_ASSC_INSTRUCT': 'Associate: Scan rewards code to redeem.',
        'RWD_ENROLL': 'Enroll now',
        'RWD_LINKEXISTING': 'Link account',
        'RWD_VIEW': 'View',
        'RWD_DONE': 'Done',
        'RWD_DASHBOARD_ERROR': 'We were unable to retrieve your rewards detail at this time.  Please try again later.',
        'RWD_WAIT_ENROLL': 'Please wait while we enroll you in the rewards program...',
        'RWD_PHN_MISSING': 'Please enter the 10 digit Phone # (xxx-xxx-xxxx) associated with your Rewards Member Number.',
        'RWD_EXT': 'Ext:',
        'RWD_NEW_MEM': 'New Rewards Member Sign-up',
        'RWD_ACT_TYPE': 'Account Type: ',
        'RWD_BSNS': 'Business',
        'RWD_PERS': 'Personal',
        'RWD_TCH': 'Teacher',
        'RWD_SEL_ACT_TYPE': 'Please select an account type.',
        'RWD_FRST_NAME': 'First Name: ',
        'RWD_FNAME_ERR': 'Please enter a first name.',
        'RWD_LST_NME': 'Last Name: ',
        'RWD_LNAME_ERR': 'Please enter a last name.',
        'RWD_ADDR': 'Address: ',
        'RWD_ADD_L1': 'Address Line 1: ',
        'RWD_ADD_L1_ERR': 'Please enter a street address',
        'RWD_ADD_L2': 'Address Line 2: ',
        'RWD_CITY': 'City: ',
        'RWD_ENTR_CITY': 'Please enter a city or town name.',
        'RWD_ST': 'State: ',
        'RWD_STT_ERR': 'Please select a state.',
        'RWD_ZIP': 'Zip: ',
        'RWD_ZIP_ERR': 'Please enter a zip code.',
        'RWD_PHN': 'Phone: ',
        'RWD_PHN_PH': 'Rewards Phone Number',
        'RWD_PHN_ERR': 'Please enter a 10 digit Phone # (xxx-xxx-xxxx).',
        'RWD_AREA_ERR': 'Phone number is not valid or area code not greater than 199',
        'RWD_DEL_MTH': 'Delivery Method: ',
        'RWD_MTH': 'Method*',
        'RWD_EML': 'eMail',
        'RWD_PST': 'Postal',
        'RWD_DEL_MTH_ERR': 'Please select a delivery method.',
        'RWD_PLS_NEW_ACCT': 'Please wait while we register your new account',
        'RWD_NUMBER_ERR': 'Please enter a valid Rewards Member Number.',
        'RWD_NUMBERLEN_ERR': 'The Rewards Member Number must be at least 2 digits and is usually 10.',
        'RWD_ADDRESS_ERR': 'Please enter an address.',
        'RWD_LINK_ABOUT': 'About Staples Rewards',
        'RWD_LINK_TERMS': 'Terms & Conditions',
        'RWD_SIGNUP': 'Sign up for free now and enjoy <b>5% back<br>in Rewards</b> and <b>free shipping on orders over $14.99.</b>',
        'RWD_GETUPTO': 'Get up to ',
        'RWD_5PCT': '5% back ',
        'RWD_FREESHIP': 'in rewards and free shipping.',
        'RWD_EXCLUSIONS': 'Exclusions apply.',
        'RWD_ERROR_TITLE': 'REWARDS ERROR',
        'RWD_REDEEM_TITLE': 'REDEEM REWARD',
        'RWD_ATC_TITLE': 'ADDED TO CART',
        'RWD_VIEWCART': 'VIEW CART',
        'RWD_CHKOUT': 'CHECKOUT',
        'RWD_EARNED_REWARD': 'Earned Reward',
        'RWD_EARNED_INK_REWARD': 'Earned Ink Reward',
        'RWD_ACCT_ALREADY': 'Already got an account?  Link it to your Staples user profile.',

        'SF_F1_LABEL': 'Computer Workstation',
        'SF_F2_LABEL': 'Mobile Phones',
        'SF_F4_LABEL': 'U.S. Postal Service&reg;',
        'SF_CPC_LABEL': 'Copy & Print Services',
        'SF_FSU_LABEL': 'Full-service UPS&reg; Shipping',
        'SF_ISP_LABEL': 'Buy online. Pickup in store.',
        'SF_MPR_LABEL': 'Mobile Printing',
        'SF_STS_LABEL': 'Ship to Store',
        'SF_TS_LABEL': 'Technology Services',
        'SF_UPS_LABEL': 'UPS&reg; Prepaid Drop-off',
        'SF_F1_TOOLTIP': 'Private rental areas with Microsoft<sup>&reg;</sup> Office, Internet access, and printing capabilities.',
        'SF_F2_TOOLTIP': 'Top phones and accessories, plus in-store activations and upgrades from Verizon.',
        'SF_F4_TOOLTIP': 'USPS shipping services & stamps. Same low USPS rates, convenient Staples hours & up to 5% back in Staples Rewards on shipping',
        'SF_CPC_TOOLTIP': 'Print services ranging from presentations & business cards to signs & banners with expert advice from our Certified Print Pros.',
        'SF_FSU_TOOLTIP': 'Easy shipping with UPS and up to 5% back in Staples Rewards. All Staples stores accept UPS prepaid drop-off packages',
        'SF_ISP_TOOLTIP': 'We will have your online order ready at your local store within two hours. See an associate for details.',
        'SF_MPR_TOOLTIP': 'Ability to accept documents submitted through a web enabled mobile device.',
        'SF_STS_TOOLTIP': 'Free shipping to your local Staples<sup>&reg;</sup> store when you order online.',
        'SF_TS_TOOLTIP': 'Complete technology solutions for your home or office from our certified techs.',
        'SF_UPS_TOOLTIP': 'Drop off any UPS<sup>&reg;</sup> prepaid package for shipment.',

        'SKU_COUPON1': 'Instant Savings: ',
        'SKU_COUPON2': 'Price After Instant Savings: ',
        'SKU_REBATE1': 'Rebate: ',
        'SKU_REBATE2': 'Now: ',
        'SKU_REBATE3': 'Price After Rebate: ',
        'SKU_PROD_DETAIL_HEADER': 'Description',
        'SKU_PROD_ITEM_LABEL': 'Item: ',
        'SKU_PROD_MODEL_LABEL': 'Model: ',
        'SKU_PROD_SEE_MORE': 'Read full description',
        'SKU_PROD_SEE_LESS': 'See Less',
        'SKU_NO_REVIEWS_LABEL': 'No product reviews found.',
        'SKU_REVIEWS_LABEL': 'Reviews',
        'SKU_REVIEWS_HEADER': 'Product Reviews',
        'SKU_REVIEWS_DISPLAY': 'Displaying {{pageStart}} - {{pageEnd}}',
        'SKU_REVIEWS_BY': 'By',
        'SKU_REVIEWS_VBUYER': 'Verified Buyer',
        'SKU_SPECS_LABEL': 'Specifications',
        'SKU_FREE_SHIPPING': 'Free shipping',
        'SKU_FORALL_REWARDS': 'for all rewards customers.',
        'SKU_REWARDS_THRESHOLD': ' on orders over $14.99',
        'SKU_REG_PRICE_LBL': 'Reg',
        'SKU_MASTER_SELECT_LBL': 'Select an item',
        'SKU_BOPIS_OOS_ONLINE': 'Out of stock online',
        'SKU_ONLINE_ONLY': 'Available online only',
        'SKU_INSTORE_ONLY': 'Available in-store only',
        'SKU_SHIPPING_LBL': 'Shipping',
        'SKU_TO_STORE': 'to store',
        'SKU_FOR_REWARDS': 'on orders over $14.99 for Staples Rewards members',
        'SKU_REVIEW_MOST_LIKE_POS': 'Most liked positive',
        'SKU_REVIEW_MOST_LIKE_NEG': 'Most liked negative',
        'SKU_REVIEWS_SEEALL': 'See all reviews',
        'SKU_OOS_BTN': 'Out of stock',
        'SKU_INSTORE_BTN': 'For sale in store only',
        'SKU_OOSSTORE_BTN': 'Out of stock in selected store',
        'SKU_OOSONLINE_BUTPU': 'This item is out of stock online, but available for <strong>pick up today</strong>.',

        'SM_BUSINESS': '10+ Employee Businesses',
        'SM_STORE': 'Find a Store',
        'SM_AD': 'Shop our Weekly Ad',
        'SM_COUPONCENTER': 'See Deals & Coupons',
        'SM_REWARDS': 'Rewards',
        'SM_CAT': 'Shop By Category',
        'SM_NUM': 'ORDER BY ITEM NUMBER',
        'SM_TECH': 'Shop Technology',
        'SM_CLEAN': 'Shop Cleaning & Breakroom',
        'SM_CLEAR': 'Shop Clearance',
        'SM_NEW': 'WHAT\'S NEW',
        'SM_DEAL': 'Hot Deals',
        'SM_COUPON': 'Coupon Wallet',
        'SM_FAV': 'My Favorites Lists',
        'SM_ORDER': 'Easy Reorder',
        'SM_ORDER_DESC': 'Items ordered in the past 12 months.',
        'SM_ORDER_ERROR_MSG': 'There was an error gathering your order history.  Please try again later.',
        'SM_MY_ORDER': 'My Orders',
        'SM_INK': 'Ink &amp; Toner Finder',
        'SM_ACCT': 'My Account',
        'SM_LOGIN': 'Sign in',
        'SM_LOGOUT': 'Logout',
        'SM_OPTIN': 'Sign-up for deals',
        'SM_FOLLOW': 'Follow Us',
        'SM_APP': 'Download App',
        'SM_DESKTOP': 'View Full Site',
        'SM_HELP': 'Help Center',
        'SM_HELLO': 'Hello',
        'SM_REBATES': 'Rebate Center',
        'SM_PRINT_SERVICES': 'Print & Marketing Services',

        'SRCH_PLACEHOLDER': 'Search millions of items',
        'SRCH_HEADER': 'Search',
        'SRCH_CANCEL': 'CANCEL',
        'SRCH_INK_TONER_FINDER': 'INK & TONER FINDER',
        'SRCH_INK_TONER_SearchBy': 'Search by cartridge, model number or brand',
        'SRCH_KEYWORD_MATCHES': 'KEYWORD MATCHES',
        'SRCH_RECENT_SEARCHES': 'Recently Searched',
        'SRCH_RECENT_ORDER': 'Recently Ordered',
        'SRCH_MORE_ORDER': 'More',
        'SRCH_ONLY_AVAILABLE': 'Only show products available',
        'SRCH_IN_THISSTORE': 'In This Store:',
        'SRCH_IN_MYSTORE': 'In My Store:',
        'SRCH_STPLS_STORE': 'Staples Store ',

        'STPLS_COPY': 'Staples, Inc.',
        'STPLS_APP': 'Download the app',

        'NAV_CAT': 'Browse Categories',

        'TAB_STORE': 'STORE FINDER',
        'TAB_ACCT': 'ACCOUNT',
        'TAB_MORE': 'MORE',

        'ERR_HEADER': 'Whoops',
        'ERR_PAGENOTFOUND': 'Page Not Found'

    });

}]);

})();
